### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by ShoiraTa**
# Milestone 2: User interface 
- displaying 3X3 board and prompts for users
- collecting user inputs
- main.rb is responsible for interaction with users and has a very basic flow with user input validation

### CODE REVIEW

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_  Changes Requested :recycle:

### Hello Shoira Toshpulatova

You have done great so far :+1: However, there are some changes that you need to make in order to get your project approved

- [x] user input should be validated so it's not empty. ( users should not be able to create an empty name)

empty



- [x] Game should inform players if the selected move is a winning move. [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_win%2059.png)

win


- [x] You should have a main branch and a development branch as default. Kindly create a main branch
<hr>


Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Comment by ShoiraTa** [comment]
Hello, 
Thank you for your comments, I worked on the requested changes. Now empty answers are not validated.  The main branch is created. 
Thank you

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_  Changes Requested :recycle:

### Hello Shoira Toshpulatova


Good job with the changes you made after the last review :+1:,
However, there are some changes that you need to make in order to get your project approved

- [x] user input should be validated so it's not empty. ( users should not be able to create an empty username)
```sh
 Kindly add a function that will check if the user input is not empty, otherwise ask the user to enter a valid user name )

```
 


Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Comment by ShoiraTa** [comment]
Hello, 
I misunderstood the previous comment and was validating user answer input. 
This time user name is validated as well (true if name.length >= 3 && !name.nil?).
Thank you for your kind support ))

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: 

**Congratulations on work done so far and thanks for adopting the code review changes from the previous TSE. User inputs are now being validated but it's not done correctly.**

- [ ] **You have a bug in your code. It might be difficult to detect it but it's there. I tried an empty name for player 2 and it told me "Please enter a valid name, it should have at least 3 characters" as expected. However, after entering the valid name, I continued to receive the same feedback. Please see the screenshot.**
shoirata2

**Please fix the little bug and request for another review once you're done.**

**Please don't give up, you're almost there.** :muscle: 

**Happy coding**!!!

**Comment by ShoiraTa** [comment]
Hello, 
Thank you for informing me about the bug, I can see the importance of being attentive to details now. 
The bug is fixed.

**Review by mricanho — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @ShoiraTa, you smashed this milestone, excellent work on your user interface🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

that's how you do it

Now you can merge this branch 🚀 

You can contact me on slack if you have any questions, just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

**Pull request merged**
